global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'monitor'

receivers:
  - name: 'monitor'
    webhook_configs:
      - url: 'http://localhost:5000/alert'
