groups:
  - name: container_alerts
    rules:
      - alert: HighCpuUsage
        expr: sum(rate(container_cpu_usage_seconds_total{image!="",container_name!=""}[5m])) by (container_name) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Uso alto de CPU en el contenedor {{ $labels.container_name }}"
          description: "El uso de CPU ha superado el 80% durante más de 5 minutos."

      - alert: ContainerNotRunning
        expr: time() - container_last_seen{image!="",container_name!=""} > 5
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "Contenedor no en ejecución: {{ $labels.container_name }}"
          description: "El contenedor {{ $labels.container_name }} no ha sido visto en los últimos 5 minutos."
